name: prod
on: [push]
jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: remove .git
      run: rm -rf .git
    - name: Deploy
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        source: "*"
        target: "${{ secrets.DEPLOY_PATH }}"
        overwrite: true
        rm: false
